#!/bin/sh
# Run the current M5 concurrent-object scaffold gates.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

"$ROOT/tools/ci/m5_nbtab_model.sh"
"$ROOT/tools/ci/m5_tab_emptyhash.sh"
"$ROOT/tools/ci/m5_tab_retire.sh"
"$ROOT/tools/ci/m5_tab_chain_order.sh"
"$ROOT/tools/ci/m5_tab_node_publish.sh"
"$ROOT/tools/ci/m5_tab_array_publish.sh"
"$ROOT/tools/ci/m5_tab_slot_snapshot.sh"
"$ROOT/tools/ci/m5_strtab_prep.sh"
"$ROOT/tools/ci/m5_strtab_cas.sh"
"$ROOT/tools/ci/m5_itype_nan.sh"
"$ROOT/tools/ci/m5_math_random_tg.sh"
"$ROOT/tools/ci/m5_gcroot_publish.sh"
"$ROOT/tools/ci/m5_metatable_publish.sh"
"$ROOT/tools/ci/m5_registry_root.sh"
"$ROOT/tools/ci/m5_nomm_cache.sh"
"$ROOT/tools/ci/m5_os_reentrant.sh"
"$ROOT/tools/ci/m5_state_owner.sh"
"$ROOT/tools/ci/m5_tmpbuf_tg.sh"
"$ROOT/tools/ci/m5_threading_alloc.sh"
"$ROOT/tools/ci/m5_threading_publish.sh"
"$ROOT/tools/ci/m5_jit_profile_publish.sh"
"$ROOT/tools/ci/m5_jit_table_fload_mutable.sh"
"$ROOT/tools/ci/m5_runtime_publish.sh"
"$ROOT/tools/ci/m5_upvalue_publish.sh"
"$ROOT/tools/ci/m5_table_parser_publish.sh"
"$ROOT/tools/ci/m5_x64_uv_publish.sh"
"$ROOT/tools/ci/m5_x64_table_next_snapshot.sh"
"$ROOT/tools/ci/m5_x64_itern_snapshot.sh"
"$ROOT/tools/ci/m5_parser_capture_meta.sh"
"$ROOT/tools/ci/m5_bcdump_compat.sh"
"$ROOT/tools/ci/m5_cell_ops.sh"
"$ROOT/tools/ci/m0_guardrails.sh"

echo "M5 concurrent-object scaffold tests passed"
